@URL = http://localhost:3000
@access_token = 

###
POST {{URL}}/quotes HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
  "author": "Steve moke",
  "quote":"yes yes yes"
}

###
GET {{URL}}/quotes HTTP/1.1

###
@id = 1
GET {{URL}}/quotes/{{id}} HTTP/1.1

###
PUT {{URL}}/quotes/2 HTTP/1.1
content-type: application/json

{
  "id": 2,
  "author": "Mike",
  "quote":"sdkjfskjdfh"
}


###
DELETE {{URL}}/quotes/2 HTTP/1.1