@URL = http://localhost:3000

###
POST {{URL}}/authentication/register HTTP/1.1
content-type: application/json

{
  "email": "email@email.com",
  "name":"hsflh", 
  "password":"123456789"
}






###
POST {{URL}}/authentication/log-in HTTP/1.1
content-type: application/json

{
  "email": "hello@hello.com",
  "password": "123456789"
}


# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZmJiNWZlNi0yYTQ0LTRlZWYtYTc5Mi0yYmY3Y2M2OGViMDEiLCJpYXQiOjE2Nzg0MTA3MTEsImV4cCI6MTY3ODQ5NzExMX0.1UGdC4UHuWDYQgI-lr9Yy8ySmiDyNeMGAGyJDWRwSOA