@URL = http://localhost:3000

###
POST {{URL}}/authentication/register HTTP/1.1
content-type: application/json

{
  "email": "email@email.com",
  "name":"hsflh", 
  "password":"123456789"
}






###
POST {{URL}}/authentication/login HTTP/1.1
content-type: application/json

{
  "email": "hello@hello.com",
  "password": "123456789"
}

