@URL = http://localhost:3000

###
POST {{URL}}/users HTTP/1.1
content-type: application/json

{
  "email": "user@user.com",
  "name": "Michael Jackson"
,  "password":"123456789"
}

###
@email = user@user.com
GET {{URL}}/users/{{email}} HTTP/1.1
